WebApplication1/Models/StudentInfo.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace Models
{
    public class StudentInfo
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Img { get; set; }
        public double Fee { get; set; }
        public string Notes { get; set; }

     }
}

WebApplication1/Controllers/HomeController.cs
using Comon2;
using System;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/MailController.cs
using Comon2;
using System;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class MailController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SendMail(HttpPostedFileBase file)
        { 
            try
            {
            string _path = "";

                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                     _path = Path.Combine(Server.MapPath("~/assets/img"), _FileName);

                    file.SaveAs(_path);
                }
           
                    
            // get info from view
            var from = ConfigurationManager.AppSettings["FromEmailAddress"].ToString();
            var to = Request["to"];
            var subject = Request["subject"];
            var notes = Request["notes"];
            var content = System.IO.File.ReadAllText(Server.MapPath("~/assets/templateMail/mail.html"));

            content = content.Replace("{{From}}", from);
            content = content.Replace("{{To}}", to);
            content = content.Replace("{{Subject}}", subject);
            content = content.Replace("{{Notes}}", notes);

            System.Diagnostics.Debug.WriteLine("ok", to);

            // send mail
            new MailHelper().SendMail(to, subject, content, _path);
            ViewBag.Message = "Send mail to \"" + to + "\" success";
            }
            catch
            {
                ViewBag.Message = "Send mail failed!!!, email or pass invalid!!!";
            }
            return View("Result");
        }
    }
}

WebApplication1/Controllers/StudentController.cs
using Comon2;
using Models;
using System;
using System.Configuration;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class StudentController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Save(HttpPostedFileBase file)
        { 
            try
            {
            string imgLink = "";

                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    imgLink = "/assets/img/" + _FileName;
                    string _path = Path.Combine(Server.MapPath("~/assets/img"), _FileName);

                    file.SaveAs(_path);
                }
           
                    
                // get info from view
                var id = Request["id"];
                var name = Request["name"];
                var dob = Request["dob"];
                var gender = Request["gender"];
                 
                var fee = Request["fee"];
                var notes = Request["notes"];
                string path = Server.MapPath("~/assets/file/StudentInfo.txt");
                string[] lines = { id, name, dob, gender, fee, notes, imgLink };
                System.IO.File.WriteAllLines(path,lines);

                return RedirectToAction("show");
            }
            catch
            {
                ViewBag.Message = "Add student failed!!!";
                return View("Show");
            }

            return View("Show");
        }

        public ActionResult show()
        {
            ViewBag.Message = "Your contact page.";

            string path = Server.MapPath("~/assets/file/StudentInfo.txt");
            string[] lines =
            System.IO.File.ReadAllLines(path);

            StudentInfo student = new StudentInfo();
            student.Id = lines[0];
            student.Name = lines[1];
            student.DOB = lines[2];
            student.Gender = lines[3];
            student.Fee = Convert.ToDouble(lines[4]);
            student.Notes = lines[5];
            student.Img = lines[6];
            System.Diagnostics.Debug.WriteLine(student.Img);

            return View("Show", student);
        }
    }
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row" style="margin:200px 0">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 align-self-center">
        <div class="col-sm-6">
            <a href="/Mail" class="btn btn-block btn-danger">
                Bài 1: Send mail
            </a>
        </div>
        <div class="col-sm-6">
            <a href="/Student" class="btn btn-block btn-success">
                Bài 2: Lưu đọc sinh viên
            </a>
        </div>
    </div>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DotNet Lab", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bài 1: Send Mail", "Index", "Mail")</li>
                    <li>@Html.ActionLink("Bài 2: Lưu, Xem Sinh viên", "Index", "Student")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Student";
}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 align-self-center">
        <form action="/Student/Save" method="post" enctype="multipart/form-data" style=" display: flex; flex-direction: column; align-items: center;">
            <h2>Lưu, đọc sinh viên</h2>
            <div class="form-group">
                <label for="fromEmail">Mã học viên:</label>
                <input name="id" required type="text" class="form-control" id="fromEmail">
            </div>
            <div class="form-group">
                <label for="name">Họ tên:</label>
                <input name="name" required type="text" class="form-control" id="toEmail">
            </div>
            <div class="form-group">
                <label for="subject">Ngày sinh:</label>
                <input name="dob" required type="text" class="form-control" id="subject">
            </div> <div class="form-group">
                <label>Giới tính:</label>

                <div class="radio">
                    <label><input type="radio" name="gender" value="male" checked>Nam</label>
                </div>
                <div class="radio">
                    <label><input type="radio" name="gender" value="female">Nữ</label>
                </div>

            </div>
            <div class="form-group">
                <label for="attachment">Hình:</label>
                <input name="file" required type="file" class="form-control" id="attachment">
            </div>
            <div class="form-group">
                <label for="toEmail">Học phí:</label>
                <input name="fee" required type="number" class="form-control" id="toEmail">
            </div>
            <div class="form-group">
                <label for="notes">Ghi chú:</label>
                <textarea name="notes" class="form-control" id="notes" rows="3"></textarea>
            </div>
            <div>
                <a href="/student/show" class="btn btn-outline-primary">Xem</a>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
    <div class="col-sm-3"></div>
</div>

WebApplication1/Views/Student/Show.cshtml
@model Models.StudentInfo
@{
    ViewBag.Title = "Student Show";
}
<div class="row">
    <div class="col-sm-3"></div>
    <div class="col-sm-6 align-self-center">
        <form action="/Student/Save" method="post" enctype="multipart/form-data" style=" display: flex; flex-direction: column; align-items: center;">
            <h2>Lưu, đọc sinh viên</h2>
            <div class="form-group">
                <label for="fromEmail">Mã học viên:</label>
                <input name="id" required type="text" class="form-control" value="@Model.Id" id="fromEmail">
            </div>
            <div class="form-group">
                <label for="name">Họ tên:</label>
                <input name="name" required type="text" class="form-control" value="@Model.Name"  id="toEmail">
            </div>
            <div class="form-group">
                <label for="subject">Ngày sinh:</label>
                <input name="dob" required type="text" class="form-control" value="@Model.DOB"  id="subject">
            </div> <div class="form-group">
                <label>Giới tính:</label>

                <div class="radio">
                    <label><input type="radio" name="gender" value="male" checked>Nam</label>
                </div>
                <div class="radio">
                    <label><input type="radio" name="gender" value="female">Nữ</label>
                </div>

            </div>
            <div class="form-group">
                <img src="@Model.Img" alt="st" style="max-height:100px; max-height:100px" />
            </div>
            <div class="form-group">
                <label for="toEmail">Học phí:</label>
                <input name="fee" required type="number" class="form-control"  value="@Model.Fee"  id="toEmail">
            </div>
            <div class="form-group">
                <label for="notes">Ghi chú:</label>
                <textarea name="notes" class="form-control" id="notes" rows="3">@Model.Notes</textarea>
            </div>
            <div>
                <a href="/student/show" class="btn btn-outline-primary">Xem</a>
                <a href="/student" class="btn btn-primary">From Thêm</a>
            </div>
        </form>
    </div>
    <div class="col-sm-3"></div>
</div>